# Site settings

baseurl: "" # the subpath of your site, e.g. /portfolio
url: "" # the base hostname & protocol for your site
language: "" # language to set into html tag, default is en

# User settings

author: André M Fagundes
author-title: Desenvolvedor Web Sênior
gravatar: 86ca72b75ff984ae58bd6bb5711097b2
email: amfcom@gmail.com
twitter: amfcom
github: andrefagundes
facebook: andremacielfagundes
linkedin: andremfagundes
bio: "Desenvolvedor Web desde meados 2006, apaixonado por jogos, música.
      Formado em Ciências da Computação, focado nas melhores tecnologias do mundo atual para desenvolver aplicações seguras, intuitivas e de alta performance. 
      Conhecimento em várias linguagens de programação, vários frameworks de ponta e em configurações de servidores linux e nuvem para entrega de projetos robustos e com segurança. 
      Trabalhei em vários órgãos do governo federal como Ministérios da Educação, Saúde, Ciência e Tecnologia."

# Skills
#
# I'll use five differents levels:
# 1 - Studying: You know the basics of the skill and is studying it to get better
# 2 - Padawan: You know a little more than the basics and is comfortable to work with it
# 3 - Work with: You know how to handle the skill and how to properly use it in a real project
# 4 - Specialist: You have advanced knowledge of the skill and know how to use its best practices in a real project
# 5 - Jedi: You master the skill, know how and when to use and when not use it
#
# You can change these names in _includes/_skill-level-name.html if you wish
#
# If you don't want one of the sections below, leave the variable without any values teste
front-end:
  - name: HTML 5
    level: 5
  - name: CSS 3
    level: 5
  - name: JavaScript
    level: 5
  - name: jQuery
    level: 5
  - name: Angular
    level: 3
  - name: React
    level: 3
  - name: React Native
    level: 3
  - name: Bootstrap
    level: 5
  - name: Vuejs
    level: 4 
  - name: Materialize CSS
    level: 4
  - name: LESS
    level: 3
  - name: SASS
    level: 3
  - name: Gulp
    level: 4
  - name: Grunt
    level: 3
  - name: Bower
    level: 3
    
back-end:
  - name: PHP
    level: 5
  - name: Node.js
    level: 5
  - name: Ruby
    level: 3

mobile:
  - name: Android
    level: 2
  - name: Apache Cordova
    level: 3
  - name: Ionic
    level: 3
  - name: NativeScript
    level: 3
  - name: Flutter
    level: 4


db:
  - name: MySQL
    level: 5
  - name: PostgreSQL
    level: 5
  - name: MongoDB
    level: 4
  - name: SQL Server
    level: 2
  - name: Oracle
    level: 3
  - name: Firebase
    level: 4
  - name: NoSQL
    level: 4

devops:
  - name: Docker
    level: 2
  - name: Vagrant
    level: 5
  - name: Jenkins
    level: 3
  - name: Git
    level: 5
  - name: Apache
    level: 4
  - name: Continuous Integration
    level: 4
  - name: Continuous Delivery
    level: 2

methodologies:
  - name: Agile Methodologies
    level: 3
  - name: Scrum
    level: 4
  - name: RUP
    level: 3

others:
  - name: Zend
    level: 5
  - name: PhalconPHP
    level: 5
  - name: Laravel
    level: 4
  - name: Ruby on Rails
    level: 3
  - name: MEAN Stack
    level: 4
  - name: Web Services
    level: 5
  - name: REST
    level: 5

# Build settings

markdown: kramdown
highlighter: rouge
sitemap: true # Generate sitemap.xml

sass:
  sass_dir: css
  style: compressed
## For more settings: https://jekyllrb.com/docs/configuration/

# exclude files if no need build
exclude: ['package.json', 'node_modules', 'README.md', 'LICENSE']

# Gems
gems: [jekyll-sitemap]
